node{
  
stage('SCM Checkout')
{
  
git 'https://github.com/tmukherjee914/Learning2.git'
}
stage('Compile Package')
{
  
  def mvnHome = tool name: 'MAVEN_HOME', type: 'maven'
  sh "${mvnHome}/bin/mvn package"
  
}
  stage('Deploy')
{
  rtMaven.run pom:pom.xml,goals;'clean install'
 
  
}
}
