node{
  
stage('SCM Checkout')
{
  
git 'https://github.com/tmukherjee914/Learning2.git'
}
stage('Compile Package')
{
  
  def mvnHome = tool name: 'MAVEN_HOME', type: 'maven'
  sh "${mvnHome}/bin/mvn package"
  
}
  stage('Deploy')
{
  
  def mvnHome = tool name: 'MAVEN_HOME', type: 'maven'
  sh "${mvnHome}/Users/test/.jenkins/workspace/my_first_pipeline/Demo_amazon2"
  sh 'mvn clean install'
  
}
}
