node{
  
stage('SCM Checkout')
{
  
git 'https://github.com/tmukherjee914/Learning2'
}
stage('Compile Package')
{
  
  def mvnHome = tool name: 'MAVEN_HOME', type: 'maven'
  sh "${mvnHome}/bin/mvn package"
}
}
